version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: khvd-mariadb
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - mariadb_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - khvd-network
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      interval: 10s
      timeout: 5s
      retries: 5

  khvd-2025:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: khvd-2025
    ports:
      - '2025:3000'
    env_file:
      - .env
    environment:
      # Application environment
      - NODE_ENV=production
      - ORIGIN=${ORIGIN:-http://localhost:2025}
      # Timezone configuration
      - TZ=Asia/Seoul
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - khvd-network
    volumes:
      # Mount timezone data for accurate time
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

networks:
  khvd-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
