version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: khvd-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/certbot:/var/www/certbot:ro
    depends_on:
      - khvd-2025
    restart: unless-stopped
    networks:
      - khvd-network

  mariadb:
    image: mariadb:latest
    container_name: khvd-mariadb
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - mariadb_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - khvd-network
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      interval: 10s
      timeout: 5s
      retries: 5

  khvd-2025:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: khvd-2025
    expose:
      - '3000'
    env_file:
      - .env
    environment:
      # Application environment
      - NODE_ENV=production
      - ORIGIN=${ORIGIN:-http://localhost:2025}
      # Timezone configuration
      - TZ=Asia/Seoul
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - khvd-network
    volumes:
      # Mount timezone data for accurate time
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  certbot:
    image: certbot/certbot:latest
    container_name: khvd-certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/certbot:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --quiet; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped
    networks:
      - khvd-network

networks:
  khvd-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
