version: '3.8'

services:
  khvd-2025:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: khvd-2025
    ports:
      - "2025:3000"
    env_file:
      - .env
    environment:
      # Application environment
      - NODE_ENV=production
      - ORIGIN=${ORIGIN:-http://localhost:2025}
    extra_hosts:
      # Allow container to connect to host machine's MySQL
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - khvd-network

networks:
  khvd-network:
    driver: bridge
